name: Node.js Package

on:
  release:
    types: [created]

env:
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: yarn install
        
      - name: Lint files
        run: yarn lint

      - name: Run tests
        run: yarn test
        
      - name: Static check
        run: yarn tsc --noEmit

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@giggleaway'
          always-auth: true

      - name: Install deps
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Build from typescript
        run: yarn build

      - name: Create .npmrc file
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" >> ~/.npmrc

      - name: Publish package to github
        run: yarn publish
