name: Test and lint

on:
  push:
    branches:
      - "main"

env:
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: yarn install
        
      - name: Lint files
        run: yarn lint

      - name: Run tests
        run: yarn test
        
      - name: Static check
        run: yarn tsc --noEmit
